summarizer:
  hide_abs_number_contribution_waterfall_chart: true
  hide_roi_values_spend_vs_contribution_chart: true
  max_channels_response_curves: 8

optimizer:
  max_channels_response_curves: 8

comparison_metrics:
  digital_channels: ["digital-afiliacion", "digital-meta", "digital-google", "digital-billing"] # List of digital channels to consider for the "Digital" row.

html_reports:
  font:
    family: '"Space Grotesk"'
    link: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap"
